server:
  port: 8089
  servlet:
    context-path: /mpag
  application:
    name: mpag
spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
feign:
  httpclient:
    sslcontext:
      enabled: true
